// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xendorser.proto

package com.baidu.xuper.pb;

public final class XendorserOuterClass {
  private XendorserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EndorserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.EndorserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.pb.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.pb.Header header = 1;</code>
     * @return The header.
     */
    com.baidu.xuper.pb.XchainOuterClass.Header getHeader();
    /**
     * <code>.pb.Header header = 1;</code>
     */
    com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <pre>
     * 请求名(类型)
     * </pre>
     *
     * <code>string RequestName = 2;</code>
     * @return The requestName.
     */
    java.lang.String getRequestName();
    /**
     * <pre>
     * 请求名(类型)
     * </pre>
     *
     * <code>string RequestName = 2;</code>
     * @return The bytes for requestName.
     */
    com.google.protobuf.ByteString
        getRequestNameBytes();

    /**
     * <pre>
     * 请求链名
     * </pre>
     *
     * <code>string BcName = 3;</code>
     * @return The bcName.
     */
    java.lang.String getBcName();
    /**
     * <pre>
     * 请求链名
     * </pre>
     *
     * <code>string BcName = 3;</code>
     * @return The bytes for bcName.
     */
    com.google.protobuf.ByteString
        getBcNameBytes();

    /**
     * <pre>
     * 带签名的交易费Tx
     * </pre>
     *
     * <code>.pb.Transaction Fee = 4;</code>
     * @return Whether the fee field is set.
     */
    boolean hasFee();
    /**
     * <pre>
     * 带签名的交易费Tx
     * </pre>
     *
     * <code>.pb.Transaction Fee = 4;</code>
     * @return The fee.
     */
    com.baidu.xuper.pb.XchainOuterClass.Transaction getFee();
    /**
     * <pre>
     * 带签名的交易费Tx
     * </pre>
     *
     * <code>.pb.Transaction Fee = 4;</code>
     */
    com.baidu.xuper.pb.XchainOuterClass.TransactionOrBuilder getFeeOrBuilder();

    /**
     * <pre>
     * Json打包的数据
     * </pre>
     *
     * <code>bytes RequestData = 5;</code>
     * @return The requestData.
     */
    com.google.protobuf.ByteString getRequestData();
  }
  /**
   * <pre>
   * 请求参数
   * </pre>
   *
   * Protobuf type {@code pb.EndorserRequest}
   */
  public static final class EndorserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.EndorserRequest)
      EndorserRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EndorserRequest.newBuilder() to construct.
    private EndorserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EndorserRequest() {
      requestName_ = "";
      bcName_ = "";
      requestData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EndorserRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.class, com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.baidu.xuper.pb.XchainOuterClass.Header header_;
    /**
     * <code>.pb.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.pb.Header header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
      return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.pb.Header header = 1;</code>
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
    }

    public static final int REQUESTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestName_ = "";
    /**
     * <pre>
     * 请求名(类型)
     * </pre>
     *
     * <code>string RequestName = 2;</code>
     * @return The requestName.
     */
    @java.lang.Override
    public java.lang.String getRequestName() {
      java.lang.Object ref = requestName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求名(类型)
     * </pre>
     *
     * <code>string RequestName = 2;</code>
     * @return The bytes for requestName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestNameBytes() {
      java.lang.Object ref = requestName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BCNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bcName_ = "";
    /**
     * <pre>
     * 请求链名
     * </pre>
     *
     * <code>string BcName = 3;</code>
     * @return The bcName.
     */
    @java.lang.Override
    public java.lang.String getBcName() {
      java.lang.Object ref = bcName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bcName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求链名
     * </pre>
     *
     * <code>string BcName = 3;</code>
     * @return The bytes for bcName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBcNameBytes() {
      java.lang.Object ref = bcName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bcName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEE_FIELD_NUMBER = 4;
    private com.baidu.xuper.pb.XchainOuterClass.Transaction fee_;
    /**
     * <pre>
     * 带签名的交易费Tx
     * </pre>
     *
     * <code>.pb.Transaction Fee = 4;</code>
     * @return Whether the fee field is set.
     */
    @java.lang.Override
    public boolean hasFee() {
      return fee_ != null;
    }
    /**
     * <pre>
     * 带签名的交易费Tx
     * </pre>
     *
     * <code>.pb.Transaction Fee = 4;</code>
     * @return The fee.
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.Transaction getFee() {
      return fee_ == null ? com.baidu.xuper.pb.XchainOuterClass.Transaction.getDefaultInstance() : fee_;
    }
    /**
     * <pre>
     * 带签名的交易费Tx
     * </pre>
     *
     * <code>.pb.Transaction Fee = 4;</code>
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.TransactionOrBuilder getFeeOrBuilder() {
      return fee_ == null ? com.baidu.xuper.pb.XchainOuterClass.Transaction.getDefaultInstance() : fee_;
    }

    public static final int REQUESTDATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString requestData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Json打包的数据
     * </pre>
     *
     * <code>bytes RequestData = 5;</code>
     * @return The requestData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRequestData() {
      return requestData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bcName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bcName_);
      }
      if (fee_ != null) {
        output.writeMessage(4, getFee());
      }
      if (!requestData_.isEmpty()) {
        output.writeBytes(5, requestData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bcName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bcName_);
      }
      if (fee_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getFee());
      }
      if (!requestData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, requestData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest)) {
        return super.equals(obj);
      }
      com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest other = (com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getRequestName()
          .equals(other.getRequestName())) return false;
      if (!getBcName()
          .equals(other.getBcName())) return false;
      if (hasFee() != other.hasFee()) return false;
      if (hasFee()) {
        if (!getFee()
            .equals(other.getFee())) return false;
      }
      if (!getRequestData()
          .equals(other.getRequestData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + REQUESTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRequestName().hashCode();
      hash = (37 * hash) + BCNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBcName().hashCode();
      if (hasFee()) {
        hash = (37 * hash) + FEE_FIELD_NUMBER;
        hash = (53 * hash) + getFee().hashCode();
      }
      hash = (37 * hash) + REQUESTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRequestData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求参数
     * </pre>
     *
     * Protobuf type {@code pb.EndorserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.EndorserRequest)
        com.baidu.xuper.pb.XendorserOuterClass.EndorserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.class, com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.Builder.class);
      }

      // Construct using com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        requestName_ = "";
        bcName_ = "";
        fee_ = null;
        if (feeBuilder_ != null) {
          feeBuilder_.dispose();
          feeBuilder_ = null;
        }
        requestData_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserRequest_descriptor;
      }

      @java.lang.Override
      public com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest getDefaultInstanceForType() {
        return com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest build() {
        com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest buildPartial() {
        com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest result = new com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.requestName_ = requestName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.bcName_ = bcName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fee_ = feeBuilder_ == null
              ? fee_
              : feeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.requestData_ = requestData_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest) {
          return mergeFrom((com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest other) {
        if (other == com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getRequestName().isEmpty()) {
          requestName_ = other.requestName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getBcName().isEmpty()) {
          bcName_ = other.bcName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasFee()) {
          mergeFee(other.getFee());
        }
        if (other.getRequestData() != com.google.protobuf.ByteString.EMPTY) {
          setRequestData(other.getRequestData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                requestName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                bcName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getFeeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                requestData_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.baidu.xuper.pb.XchainOuterClass.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.Header, com.baidu.xuper.pb.XchainOuterClass.Header.Builder, com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.pb.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.pb.Header header = 1;</code>
       * @return The header.
       */
      public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder setHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder setHeader(
          com.baidu.xuper.pb.XchainOuterClass.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder mergeHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.Header, com.baidu.xuper.pb.XchainOuterClass.Header.Builder, com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.baidu.xuper.pb.XchainOuterClass.Header, com.baidu.xuper.pb.XchainOuterClass.Header.Builder, com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object requestName_ = "";
      /**
       * <pre>
       * 请求名(类型)
       * </pre>
       *
       * <code>string RequestName = 2;</code>
       * @return The requestName.
       */
      public java.lang.String getRequestName() {
        java.lang.Object ref = requestName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求名(类型)
       * </pre>
       *
       * <code>string RequestName = 2;</code>
       * @return The bytes for requestName.
       */
      public com.google.protobuf.ByteString
          getRequestNameBytes() {
        java.lang.Object ref = requestName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求名(类型)
       * </pre>
       *
       * <code>string RequestName = 2;</code>
       * @param value The requestName to set.
       * @return This builder for chaining.
       */
      public Builder setRequestName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求名(类型)
       * </pre>
       *
       * <code>string RequestName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestName() {
        requestName_ = getDefaultInstance().getRequestName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求名(类型)
       * </pre>
       *
       * <code>string RequestName = 2;</code>
       * @param value The bytes for requestName to set.
       * @return This builder for chaining.
       */
      public Builder setRequestNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object bcName_ = "";
      /**
       * <pre>
       * 请求链名
       * </pre>
       *
       * <code>string BcName = 3;</code>
       * @return The bcName.
       */
      public java.lang.String getBcName() {
        java.lang.Object ref = bcName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bcName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求链名
       * </pre>
       *
       * <code>string BcName = 3;</code>
       * @return The bytes for bcName.
       */
      public com.google.protobuf.ByteString
          getBcNameBytes() {
        java.lang.Object ref = bcName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bcName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求链名
       * </pre>
       *
       * <code>string BcName = 3;</code>
       * @param value The bcName to set.
       * @return This builder for chaining.
       */
      public Builder setBcName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bcName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求链名
       * </pre>
       *
       * <code>string BcName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBcName() {
        bcName_ = getDefaultInstance().getBcName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求链名
       * </pre>
       *
       * <code>string BcName = 3;</code>
       * @param value The bytes for bcName to set.
       * @return This builder for chaining.
       */
      public Builder setBcNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bcName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.baidu.xuper.pb.XchainOuterClass.Transaction fee_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.Transaction, com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder, com.baidu.xuper.pb.XchainOuterClass.TransactionOrBuilder> feeBuilder_;
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       * @return Whether the fee field is set.
       */
      public boolean hasFee() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       * @return The fee.
       */
      public com.baidu.xuper.pb.XchainOuterClass.Transaction getFee() {
        if (feeBuilder_ == null) {
          return fee_ == null ? com.baidu.xuper.pb.XchainOuterClass.Transaction.getDefaultInstance() : fee_;
        } else {
          return feeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       */
      public Builder setFee(com.baidu.xuper.pb.XchainOuterClass.Transaction value) {
        if (feeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fee_ = value;
        } else {
          feeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       */
      public Builder setFee(
          com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder builderForValue) {
        if (feeBuilder_ == null) {
          fee_ = builderForValue.build();
        } else {
          feeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       */
      public Builder mergeFee(com.baidu.xuper.pb.XchainOuterClass.Transaction value) {
        if (feeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            fee_ != null &&
            fee_ != com.baidu.xuper.pb.XchainOuterClass.Transaction.getDefaultInstance()) {
            getFeeBuilder().mergeFrom(value);
          } else {
            fee_ = value;
          }
        } else {
          feeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       */
      public Builder clearFee() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fee_ = null;
        if (feeBuilder_ != null) {
          feeBuilder_.dispose();
          feeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder getFeeBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getFeeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.TransactionOrBuilder getFeeOrBuilder() {
        if (feeBuilder_ != null) {
          return feeBuilder_.getMessageOrBuilder();
        } else {
          return fee_ == null ?
              com.baidu.xuper.pb.XchainOuterClass.Transaction.getDefaultInstance() : fee_;
        }
      }
      /**
       * <pre>
       * 带签名的交易费Tx
       * </pre>
       *
       * <code>.pb.Transaction Fee = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.Transaction, com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder, com.baidu.xuper.pb.XchainOuterClass.TransactionOrBuilder> 
          getFeeFieldBuilder() {
        if (feeBuilder_ == null) {
          feeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.baidu.xuper.pb.XchainOuterClass.Transaction, com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder, com.baidu.xuper.pb.XchainOuterClass.TransactionOrBuilder>(
                  getFee(),
                  getParentForChildren(),
                  isClean());
          fee_ = null;
        }
        return feeBuilder_;
      }

      private com.google.protobuf.ByteString requestData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Json打包的数据
       * </pre>
       *
       * <code>bytes RequestData = 5;</code>
       * @return The requestData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRequestData() {
        return requestData_;
      }
      /**
       * <pre>
       * Json打包的数据
       * </pre>
       *
       * <code>bytes RequestData = 5;</code>
       * @param value The requestData to set.
       * @return This builder for chaining.
       */
      public Builder setRequestData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        requestData_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Json打包的数据
       * </pre>
       *
       * <code>bytes RequestData = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requestData_ = getDefaultInstance().getRequestData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.EndorserRequest)
    }

    // @@protoc_insertion_point(class_scope:pb.EndorserRequest)
    private static final com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest();
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EndorserRequest>
        PARSER = new com.google.protobuf.AbstractParser<EndorserRequest>() {
      @java.lang.Override
      public EndorserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EndorserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EndorserRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EndorserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.EndorserResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.pb.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.pb.Header header = 1;</code>
     * @return The header.
     */
    com.baidu.xuper.pb.XchainOuterClass.Header getHeader();
    /**
     * <code>.pb.Header header = 1;</code>
     */
    com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>string ResponseName = 2;</code>
     * @return The responseName.
     */
    java.lang.String getResponseName();
    /**
     * <code>string ResponseName = 2;</code>
     * @return The bytes for responseName.
     */
    com.google.protobuf.ByteString
        getResponseNameBytes();

    /**
     * <pre>
     * 背书服务地址
     * </pre>
     *
     * <code>string EndorserAddress = 3;</code>
     * @return The endorserAddress.
     */
    java.lang.String getEndorserAddress();
    /**
     * <pre>
     * 背书服务地址
     * </pre>
     *
     * <code>string EndorserAddress = 3;</code>
     * @return The bytes for endorserAddress.
     */
    com.google.protobuf.ByteString
        getEndorserAddressBytes();

    /**
     * <pre>
     * 背书服务签名
     * </pre>
     *
     * <code>.pb.SignatureInfo EndorserSign = 4;</code>
     * @return Whether the endorserSign field is set.
     */
    boolean hasEndorserSign();
    /**
     * <pre>
     * 背书服务签名
     * </pre>
     *
     * <code>.pb.SignatureInfo EndorserSign = 4;</code>
     * @return The endorserSign.
     */
    com.baidu.xuper.pb.XchainOuterClass.SignatureInfo getEndorserSign();
    /**
     * <pre>
     * 背书服务签名
     * </pre>
     *
     * <code>.pb.SignatureInfo EndorserSign = 4;</code>
     */
    com.baidu.xuper.pb.XchainOuterClass.SignatureInfoOrBuilder getEndorserSignOrBuilder();

    /**
     * <code>bytes ResponseData = 5;</code>
     * @return The responseData.
     */
    com.google.protobuf.ByteString getResponseData();
  }
  /**
   * Protobuf type {@code pb.EndorserResponse}
   */
  public static final class EndorserResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.EndorserResponse)
      EndorserResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EndorserResponse.newBuilder() to construct.
    private EndorserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EndorserResponse() {
      responseName_ = "";
      endorserAddress_ = "";
      responseData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EndorserResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.class, com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.baidu.xuper.pb.XchainOuterClass.Header header_;
    /**
     * <code>.pb.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.pb.Header header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
      return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.pb.Header header = 1;</code>
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
    }

    public static final int RESPONSENAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object responseName_ = "";
    /**
     * <code>string ResponseName = 2;</code>
     * @return The responseName.
     */
    @java.lang.Override
    public java.lang.String getResponseName() {
      java.lang.Object ref = responseName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseName_ = s;
        return s;
      }
    }
    /**
     * <code>string ResponseName = 2;</code>
     * @return The bytes for responseName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseNameBytes() {
      java.lang.Object ref = responseName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDORSERADDRESS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object endorserAddress_ = "";
    /**
     * <pre>
     * 背书服务地址
     * </pre>
     *
     * <code>string EndorserAddress = 3;</code>
     * @return The endorserAddress.
     */
    @java.lang.Override
    public java.lang.String getEndorserAddress() {
      java.lang.Object ref = endorserAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endorserAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 背书服务地址
     * </pre>
     *
     * <code>string EndorserAddress = 3;</code>
     * @return The bytes for endorserAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEndorserAddressBytes() {
      java.lang.Object ref = endorserAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endorserAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDORSERSIGN_FIELD_NUMBER = 4;
    private com.baidu.xuper.pb.XchainOuterClass.SignatureInfo endorserSign_;
    /**
     * <pre>
     * 背书服务签名
     * </pre>
     *
     * <code>.pb.SignatureInfo EndorserSign = 4;</code>
     * @return Whether the endorserSign field is set.
     */
    @java.lang.Override
    public boolean hasEndorserSign() {
      return endorserSign_ != null;
    }
    /**
     * <pre>
     * 背书服务签名
     * </pre>
     *
     * <code>.pb.SignatureInfo EndorserSign = 4;</code>
     * @return The endorserSign.
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.SignatureInfo getEndorserSign() {
      return endorserSign_ == null ? com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.getDefaultInstance() : endorserSign_;
    }
    /**
     * <pre>
     * 背书服务签名
     * </pre>
     *
     * <code>.pb.SignatureInfo EndorserSign = 4;</code>
     */
    @java.lang.Override
    public com.baidu.xuper.pb.XchainOuterClass.SignatureInfoOrBuilder getEndorserSignOrBuilder() {
      return endorserSign_ == null ? com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.getDefaultInstance() : endorserSign_;
    }

    public static final int RESPONSEDATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString responseData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes ResponseData = 5;</code>
     * @return The responseData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResponseData() {
      return responseData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endorserAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endorserAddress_);
      }
      if (endorserSign_ != null) {
        output.writeMessage(4, getEndorserSign());
      }
      if (!responseData_.isEmpty()) {
        output.writeBytes(5, responseData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endorserAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endorserAddress_);
      }
      if (endorserSign_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getEndorserSign());
      }
      if (!responseData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, responseData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse)) {
        return super.equals(obj);
      }
      com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse other = (com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getResponseName()
          .equals(other.getResponseName())) return false;
      if (!getEndorserAddress()
          .equals(other.getEndorserAddress())) return false;
      if (hasEndorserSign() != other.hasEndorserSign()) return false;
      if (hasEndorserSign()) {
        if (!getEndorserSign()
            .equals(other.getEndorserSign())) return false;
      }
      if (!getResponseData()
          .equals(other.getResponseData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + RESPONSENAME_FIELD_NUMBER;
      hash = (53 * hash) + getResponseName().hashCode();
      hash = (37 * hash) + ENDORSERADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getEndorserAddress().hashCode();
      if (hasEndorserSign()) {
        hash = (37 * hash) + ENDORSERSIGN_FIELD_NUMBER;
        hash = (53 * hash) + getEndorserSign().hashCode();
      }
      hash = (37 * hash) + RESPONSEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getResponseData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.EndorserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.EndorserResponse)
        com.baidu.xuper.pb.XendorserOuterClass.EndorserResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.class, com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.Builder.class);
      }

      // Construct using com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        responseName_ = "";
        endorserAddress_ = "";
        endorserSign_ = null;
        if (endorserSignBuilder_ != null) {
          endorserSignBuilder_.dispose();
          endorserSignBuilder_ = null;
        }
        responseData_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.xuper.pb.XendorserOuterClass.internal_static_pb_EndorserResponse_descriptor;
      }

      @java.lang.Override
      public com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse getDefaultInstanceForType() {
        return com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse build() {
        com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse buildPartial() {
        com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse result = new com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.responseName_ = responseName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.endorserAddress_ = endorserAddress_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.endorserSign_ = endorserSignBuilder_ == null
              ? endorserSign_
              : endorserSignBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.responseData_ = responseData_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse) {
          return mergeFrom((com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse other) {
        if (other == com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getResponseName().isEmpty()) {
          responseName_ = other.responseName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEndorserAddress().isEmpty()) {
          endorserAddress_ = other.endorserAddress_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasEndorserSign()) {
          mergeEndorserSign(other.getEndorserSign());
        }
        if (other.getResponseData() != com.google.protobuf.ByteString.EMPTY) {
          setResponseData(other.getResponseData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                responseName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                endorserAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getEndorserSignFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                responseData_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.baidu.xuper.pb.XchainOuterClass.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.Header, com.baidu.xuper.pb.XchainOuterClass.Header.Builder, com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.pb.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.pb.Header header = 1;</code>
       * @return The header.
       */
      public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder setHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder setHeader(
          com.baidu.xuper.pb.XchainOuterClass.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder mergeHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.pb.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.Header, com.baidu.xuper.pb.XchainOuterClass.Header.Builder, com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.baidu.xuper.pb.XchainOuterClass.Header, com.baidu.xuper.pb.XchainOuterClass.Header.Builder, com.baidu.xuper.pb.XchainOuterClass.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object responseName_ = "";
      /**
       * <code>string ResponseName = 2;</code>
       * @return The responseName.
       */
      public java.lang.String getResponseName() {
        java.lang.Object ref = responseName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ResponseName = 2;</code>
       * @return The bytes for responseName.
       */
      public com.google.protobuf.ByteString
          getResponseNameBytes() {
        java.lang.Object ref = responseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ResponseName = 2;</code>
       * @param value The responseName to set.
       * @return This builder for chaining.
       */
      public Builder setResponseName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        responseName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string ResponseName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseName() {
        responseName_ = getDefaultInstance().getResponseName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string ResponseName = 2;</code>
       * @param value The bytes for responseName to set.
       * @return This builder for chaining.
       */
      public Builder setResponseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        responseName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object endorserAddress_ = "";
      /**
       * <pre>
       * 背书服务地址
       * </pre>
       *
       * <code>string EndorserAddress = 3;</code>
       * @return The endorserAddress.
       */
      public java.lang.String getEndorserAddress() {
        java.lang.Object ref = endorserAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endorserAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 背书服务地址
       * </pre>
       *
       * <code>string EndorserAddress = 3;</code>
       * @return The bytes for endorserAddress.
       */
      public com.google.protobuf.ByteString
          getEndorserAddressBytes() {
        java.lang.Object ref = endorserAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endorserAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 背书服务地址
       * </pre>
       *
       * <code>string EndorserAddress = 3;</code>
       * @param value The endorserAddress to set.
       * @return This builder for chaining.
       */
      public Builder setEndorserAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        endorserAddress_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 背书服务地址
       * </pre>
       *
       * <code>string EndorserAddress = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndorserAddress() {
        endorserAddress_ = getDefaultInstance().getEndorserAddress();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 背书服务地址
       * </pre>
       *
       * <code>string EndorserAddress = 3;</code>
       * @param value The bytes for endorserAddress to set.
       * @return This builder for chaining.
       */
      public Builder setEndorserAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        endorserAddress_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.baidu.xuper.pb.XchainOuterClass.SignatureInfo endorserSign_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.SignatureInfo, com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder, com.baidu.xuper.pb.XchainOuterClass.SignatureInfoOrBuilder> endorserSignBuilder_;
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       * @return Whether the endorserSign field is set.
       */
      public boolean hasEndorserSign() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       * @return The endorserSign.
       */
      public com.baidu.xuper.pb.XchainOuterClass.SignatureInfo getEndorserSign() {
        if (endorserSignBuilder_ == null) {
          return endorserSign_ == null ? com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.getDefaultInstance() : endorserSign_;
        } else {
          return endorserSignBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       */
      public Builder setEndorserSign(com.baidu.xuper.pb.XchainOuterClass.SignatureInfo value) {
        if (endorserSignBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          endorserSign_ = value;
        } else {
          endorserSignBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       */
      public Builder setEndorserSign(
          com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder builderForValue) {
        if (endorserSignBuilder_ == null) {
          endorserSign_ = builderForValue.build();
        } else {
          endorserSignBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       */
      public Builder mergeEndorserSign(com.baidu.xuper.pb.XchainOuterClass.SignatureInfo value) {
        if (endorserSignBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            endorserSign_ != null &&
            endorserSign_ != com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.getDefaultInstance()) {
            getEndorserSignBuilder().mergeFrom(value);
          } else {
            endorserSign_ = value;
          }
        } else {
          endorserSignBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       */
      public Builder clearEndorserSign() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endorserSign_ = null;
        if (endorserSignBuilder_ != null) {
          endorserSignBuilder_.dispose();
          endorserSignBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder getEndorserSignBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getEndorserSignFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       */
      public com.baidu.xuper.pb.XchainOuterClass.SignatureInfoOrBuilder getEndorserSignOrBuilder() {
        if (endorserSignBuilder_ != null) {
          return endorserSignBuilder_.getMessageOrBuilder();
        } else {
          return endorserSign_ == null ?
              com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.getDefaultInstance() : endorserSign_;
        }
      }
      /**
       * <pre>
       * 背书服务签名
       * </pre>
       *
       * <code>.pb.SignatureInfo EndorserSign = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.baidu.xuper.pb.XchainOuterClass.SignatureInfo, com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder, com.baidu.xuper.pb.XchainOuterClass.SignatureInfoOrBuilder> 
          getEndorserSignFieldBuilder() {
        if (endorserSignBuilder_ == null) {
          endorserSignBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.baidu.xuper.pb.XchainOuterClass.SignatureInfo, com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder, com.baidu.xuper.pb.XchainOuterClass.SignatureInfoOrBuilder>(
                  getEndorserSign(),
                  getParentForChildren(),
                  isClean());
          endorserSign_ = null;
        }
        return endorserSignBuilder_;
      }

      private com.google.protobuf.ByteString responseData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes ResponseData = 5;</code>
       * @return The responseData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getResponseData() {
        return responseData_;
      }
      /**
       * <code>bytes ResponseData = 5;</code>
       * @param value The responseData to set.
       * @return This builder for chaining.
       */
      public Builder setResponseData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        responseData_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bytes ResponseData = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        responseData_ = getDefaultInstance().getResponseData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.EndorserResponse)
    }

    // @@protoc_insertion_point(class_scope:pb.EndorserResponse)
    private static final com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse();
    }

    public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EndorserResponse>
        PARSER = new com.google.protobuf.AbstractParser<EndorserResponse>() {
      @java.lang.Override
      public EndorserResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EndorserResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EndorserResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_EndorserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_EndorserRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_EndorserResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_EndorserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017xendorser.proto\022\002pb\032\014xchain.proto\032\034goo" +
      "gle/api/annotations.proto\"\205\001\n\017EndorserRe" +
      "quest\022\032\n\006header\030\001 \001(\0132\n.pb.Header\022\023\n\013Req" +
      "uestName\030\002 \001(\t\022\016\n\006BcName\030\003 \001(\t\022\034\n\003Fee\030\004 " +
      "\001(\0132\017.pb.Transaction\022\023\n\013RequestData\030\005 \001(" +
      "\014\"\234\001\n\020EndorserResponse\022\032\n\006header\030\001 \001(\0132\n" +
      ".pb.Header\022\024\n\014ResponseName\030\002 \001(\t\022\027\n\017Endo" +
      "rserAddress\030\003 \001(\t\022\'\n\014EndorserSign\030\004 \001(\0132" +
      "\021.pb.SignatureInfo\022\024\n\014ResponseData\030\005 \001(\014" +
      "2c\n\tXendorser\022V\n\014EndorserCall\022\023.pb.Endor" +
      "serRequest\032\024.pb.EndorserResponse\"\033\202\323\344\223\002\025" +
      "\"\020/v1/endorsercall:\001*B)\n\022com.baidu.xuper" +
      ".pbB\023XendorserOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.baidu.xuper.pb.XchainOuterClass.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_pb_EndorserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_EndorserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_EndorserRequest_descriptor,
        new java.lang.String[] { "Header", "RequestName", "BcName", "Fee", "RequestData", });
    internal_static_pb_EndorserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_EndorserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_EndorserResponse_descriptor,
        new java.lang.String[] { "Header", "ResponseName", "EndorserAddress", "EndorserSign", "ResponseData", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.baidu.xuper.pb.XchainOuterClass.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
